### ISSUE TITLE
Empty new lines ignored in <pre> blocks

### ISSUE THREAD

**Issue by kpagacz** [jugglerchris/rust-html2text#69]
Using the latest version of `html2text`:
```toml
[package]
name = "testhtml2text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2text = "0.4.4"
```

I have this example that reproduces what I am talking about:

```rust
fn main() {
    let input = b"
<pre>
This is a preformatted block of text.

It has newlines and renders as-is written in HTML.
</pre>";
    println!(
        "{}",
        html2text::from_read_with_decorator(
            &input[..],
            120,
            html2text::render::text_renderer::TrivialDecorator::new()
        )
    );
}
```

The program outputs:
```
This is a preformatted block of text.
It has newlines and renders as-is written in HTML.
```

As I use `html2text` to parse descriptions of algorithmic problems, I would like the empty new lines to be preserved in the output because sometimes they are crucial to understanding a problem's example. E.g. https://adventofcode.com/2020/day/4

I don't have any issues with `html2text` ignoring empty new lines anywhere else but `<pre>` blocks. These tags are understood explicitly as already preformatted, and all browsers would render them as written in the source code. `html2text` is not a browser. Still, I believe preserving the intent of the HTML is beneficial in this case.

As a workaround, I am inserting `<br>` tags at the end of all lines in the `<pre>` blocks of HTML I am downloading, but that seems suboptimal at best.
